#!/bin/bash
#
# A wrapper for requireJs runner
#
CUR="${BASH_SOURCE[0]}";
if([ -h "${CUR}" ]) then
  while([ -h "${CUR}" ]) do CUR=`readlink -m "${CUR}"`; done
fi
pushd . > /dev/null
cd `dirname ${CUR}` > /dev/null
CUR=`pwd`;
popd  > /dev/null

exec "${CUR}/node_modules/camel/bin/camel" "${CUR}/emo.coffee" "${CUR}" "$@"
