###
  labels.coffee
###
define ->
    aboutness: '主客关系'
    me: '我'
    you: '你'
    it: '他'
    me_you: '我你'
    me_it: '我他'
    you_me: '你我'
    you_it: '你他'
    it_me: '他我'
    it_you: '他你'
    uncertain: '不确定'
    emotion: '表情'
    neutral: '适中'
    joy: '快乐'
    surprise: '惊奇'
    fear: '惧怕'
    sadness: '悲伤'
    digest: '厌恶'
    anger: '愤怒'
    slight: '轻蔑'
    strength: '强度'
    weakest: '最弱'
    weaker: '较弱'
    weak: '稍弱'
    modest: '适中'
    strong: '稍强'
    stronger: '较强'
    strongest: '最强'
    subjunctive: '虚拟或假设'
    positive: '是'
    negative: '否'

