###
  labels.coffee
###
define ->
    aboutness: '主客关系'
    me: '我'
    you: '你'
    it: '他'
    me_you: '我你'
    me_it: '我他'
    you_me: '你我'
    you_it: '你他'
    it_me: '他我'
    it_you: '他你'
    uncertain: '不确定'
    emotion: '表情'
    joy: '快乐'
    surprise: '惊奇'
    fear: '惧怕'
    sadness: '悲伤'
    digest: '厌恶'
    anger: '愤怒'
    scorn: '轻蔑'
    distress: '愁苦'
    anxiety: '焦虑'
    serene: '安详'
    sincere: '诚恳'
    wish: '愿念'
    pity: '怜惜'
    guilt: '惭愧'
    admire: '羡慕'
    confusion: '疑惑'
    caution: '谨慎'
    fierce: '强悍'
    trance: '恍惚'
    strength: '强度'
    unrelated: '不相关'
    modest: '适中'
    strong: '稍强'
    stronger: '较强'
    strongest: '最强'
    subjunctive: '虚拟或假设'
    positive: '是'
    negative: '否'
    spam: '广告'
    normal: '正常'

