###
  labels.coffee
###
define ->
    aboutness: '情感相关性'
    related: '相关'
    uncertain: '不确定'
    emotion: '表情'
    joy: '快乐欢欣愉悦'
    surprise: '好奇新鲜惊异'
    fear: '惧怕惊悚恐怖'
    sadness: '悲伤哀恸痛心'
    disgust: '忍耐厌恶怨恨'
    anger: '怪罪愤怒气恼'
    scorn: '轻蔑鄙视看不起'
    distress: '愁苦郁闷难受'
    anxiety: '焦虑烦躁慌张'
    serene: '安详和美静谧'
    sincere: '恳切诚恳感谢'
    wish: '想念愿望憧憬'
    pity: '怜惜恻悯惋惜'
    guilt: '惭愧懊悔内疚'
    admire: '欣赏佩服羡慕'
    envy: '嫉妒嫉恨妒恨'
    like: '喜爱爱慕好感'
    laments: '感叹赞叹慨叹'
    confusion: '不解疑惑疑问'
    caution: '谨慎小心翼翼'
    fierce: '凶狠强悍暴烈'
    trance: '恍惚不定迷茫'
    strength: '强度'
    unrelated: '不相关'
    weak: '稍弱'
    strong: '稍强'
    stronger: '较强'
    strongest: '最强'
    subjunctive: '虚拟或假设'
    positive: '是'
    negative: '否'
    spam: '广告'
    normal: '正常'

